// GENERATED by scripts/stamp.py — do not edit.
// Regenerate with `make stamp`.
self.SHELL_VERSION = "6960442b4d";
self.SHELL = [
  "./",
  "./index.html",
  "./style.css",
  "./js/audio.js",
  "./js/core.js",
  "./js/data.js",
  "./js/flashcards.js",
  "./js/learn.js",
  "./js/main.js",
  "./js/practice.js",
  "./js/stats.js",
  "./data/characters.json",
  "./manifest.webmanifest",
  "./icons/icon-192.png",
  "./icons/icon-512.png",
  "./icons/icon-maskable-512.png"
];
