// Service worker — offline support for hindlearn.
//
// Every URL here is RELATIVE on purpose: GitHub Pages serves this app from
// /hindlearn/, not from the domain root, so an absolute "/index.html" would
// 404 in production while working fine on localhost.
//
// Two caching strategies, because the app has two very different kinds of
// asset:
//
//   the shell (html, css, js, the character JSON)
//     Precached on install and served cache-first. It is small, it changes
//     together, and the app is useless without all of it.
//
//   the audio (592 MP3s, ~4.7 MB)
//     NOT precached. Downloading five megabytes on someone's mobile data
//     the first time they open a web page is rude, and most of those clips
//     are for levels they may never reach. Instead each clip is cached the
//     first time it is played, so the letters you actually drill become
//     available offline as a side effect of drilling them. The footer's
//     "Save for offline" button precaches the lot on demand, for anyone who
//     wants to prepare for a flight.
//
// sw-shell.js is generated by `make stamp` and defines SHELL_VERSION (a
// content hash of the shell files) and SHELL (the list to precache).
// Importing it rather than hardcoding a list means adding a module cannot
// silently leave it out of the offline bundle.

importScripts("./sw-shell.js");

const SHELL_CACHE = `hindlearn-shell-${self.SHELL_VERSION}`;
const AUDIO_CACHE = "hindlearn-audio-v1";

self.addEventListener("install", (event) => {
  // cache: "reload" on every shell request matters. index.html carries
  // ?v=<hash> on the stylesheet and the entry module, but the modules that
  // entry imports are fetched at bare URLs — so without this, a new shell
  // version could install a FRESH main.js next to a STALE data.js out of
  // the HTTP cache. Forcing a revalidated fetch makes the content hash the
  // only thing that decides what is in the cache.
  event.waitUntil(
    caches.open(SHELL_CACHE)
      .then((cache) => Promise.all(
        self.SHELL.map((url) =>
          fetch(new Request(url, { cache: "reload" }))
            .then((res) => { if (res.ok) return cache.put(url, res); })
        )
      ))
      // Take over without waiting for every old tab to close. The shell is
      // versioned by content hash, so a new worker always means new files.
      .then(() => self.skipWaiting())
  );
});

self.addEventListener("activate", (event) => {
  event.waitUntil(
    caches.keys()
      .then((names) => Promise.all(
        names
          // Keep the audio cache across shell upgrades: the MP3s are
          // immutable and re-downloading 4.7 MB on every deploy would
          // defeat the point.
          .filter((n) => n.startsWith("hindlearn-shell-") && n !== SHELL_CACHE)
          .map((n) => caches.delete(n))
      ))
      .then(() => self.clients.claim())
  );
});

const isAudio = (url) => url.pathname.includes("/audio/") && url.pathname.endsWith(".mp3");

self.addEventListener("fetch", (event) => {
  const req = event.request;
  if (req.method !== "GET") return;

  const url = new URL(req.url);
  if (url.origin !== self.location.origin) return;

  // Navigations: try the network so a deploy is picked up promptly, fall
  // back to the cached shell when offline.
  if (req.mode === "navigate") {
    event.respondWith(
      fetch(req).catch(() => caches.match("./index.html", { ignoreSearch: true }))
    );
    return;
  }

  if (isAudio(url)) {
    event.respondWith(
      caches.open(AUDIO_CACHE).then(async (cache) => {
        const hit = await cache.match(req);
        if (hit) return hit;
        const res = await fetch(req);
        if (res.ok) cache.put(req, res.clone());
        return res;
      })
    );
    return;
  }

  // Shell and everything else: NETWORK FIRST, cache as the offline fallback.
  //
  // Cache-first is the obvious choice here and it is wrong for this app.
  // index.html carries ?v=<hash>, but the modules it imports are bare URLs,
  // so a cache-first worker keeps serving yesterday's js/audio.js next to
  // today's index.html until every tab has closed and a new worker has taken
  // over. Observed exactly that during development: a fresh entry point
  // running a stale module, which is indistinguishable from a code bug.
  //
  // These files are a few KB each and page loads are rare, so paying one
  // round trip to be certain the app is internally consistent is the right
  // trade. Offline still works: the cached copy answers when fetch rejects.
  event.respondWith(
    fetch(req)
      .then((res) => {
        if (res.ok) {
          const copy = res.clone();
          caches.open(SHELL_CACHE).then((c) => c.put(req, copy)).catch(() => {});
        }
        return res;
      })
      .catch(() => caches.match(req, { ignoreSearch: true }))
  );
});

// "Save for offline": fetch every audio file into the audio cache, reporting
// progress so the UI can show a bar. Deliberately sequential-ish in small
// batches — firing 592 parallel requests at a phone is a good way to have
// the browser start dropping them.
self.addEventListener("message", (event) => {
  const msg = event.data || {};
  if (msg.type !== "PRECACHE_AUDIO") return;

  const urls = msg.urls || [];
  const reply = (payload) => {
    if (event.source) event.source.postMessage({ type: "PRECACHE_AUDIO_PROGRESS", ...payload });
  };

  event.waitUntil((async () => {
    const cache = await caches.open(AUDIO_CACHE);
    let done = 0, failed = 0;
    const BATCH = 8;
    for (let i = 0; i < urls.length; i += BATCH) {
      const batch = urls.slice(i, i + BATCH);
      await Promise.all(batch.map(async (u) => {
        try {
          if (await cache.match(u)) return;
          const res = await fetch(u);
          if (res.ok) await cache.put(u, res.clone()); else failed += 1;
        } catch { failed += 1; }
      }));
      done = Math.min(i + BATCH, urls.length);
      reply({ done, total: urls.length, failed });
    }
    reply({ done: urls.length, total: urls.length, failed, finished: true });
  })());
});
