#!/usr/bin/env python3
"""
Stamp the app's assets with a content hash.

Replaces the hand-maintained `?v=N` on the stylesheet and script tags, which
had to be bumped by hand on every change and was forgotten often enough to
waste real debugging time (a stale index.html quietly serving an old app.js
looks exactly like a code bug).

Two outputs, both derived from one hash of the shell files:

    index.html      every local css/js/json asset gets ?v=<hash>
    sw-shell.js     SHELL_VERSION + the SHELL list the service worker
                    precaches, globbed rather than hardcoded so a new
                    module cannot be left out of the offline bundle

Note on scope: only index.html's own references get the query string. The
modules that js/main.js imports are fetched at bare URLs, because rewriting
import specifiers would change the files being hashed and never settle. The
service worker closes that gap instead — it installs its shell with
`cache: "reload"`, so a new content hash always re-downloads every module
rather than pairing a fresh entry point with a stale import.

Run via `make stamp`. Idempotent: running it twice changes nothing.
"""
from __future__ import annotations

import hashlib
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

# Everything the app needs to boot with no network. Order is irrelevant.
SHELL_GLOBS = ["index.html", "style.css", "js/*.js", "data/*.json",
               "manifest.webmanifest", "icons/*.png"]


def shell_files() -> list[Path]:
    out: list[Path] = []
    for pattern in SHELL_GLOBS:
        out.extend(sorted(ROOT.glob(pattern)))
    return [p for p in out if p.is_file()]


def content_hash(files: list[Path]) -> str:
    h = hashlib.sha256()
    for f in sorted(files, key=lambda p: p.relative_to(ROOT).as_posix()):
        h.update(f.relative_to(ROOT).as_posix().encode())
        h.update(f.read_bytes())
    return h.hexdigest()[:10]


def stamp_index(version: str) -> bool:
    path = ROOT / "index.html"
    src = path.read_text(encoding="utf-8")

    # href="style.css?v=..." / src="js/main.js?v=..." — local assets only.
    def sub(m: re.Match) -> str:
        attr, url = m.group(1), m.group(2)
        base = url.split("?")[0]
        return f'{attr}="{base}?v={version}"'

    out = re.sub(r'\b(href|src)="((?:js/|data/|)[^"?:]+\.(?:css|js|json))(?:\?[^"]*)?"', sub, src)
    changed = out != src
    if changed:
        path.write_text(out, encoding="utf-8")
    return changed


def write_sw_shell(version: str, files: list[Path]) -> bool:
    rel = ["./"] + [f"./{p.relative_to(ROOT).as_posix()}" for p in files]
    # The stylesheet and modules are requested with ?v=<hash>; the service
    # worker matches with ignoreSearch, so the bare paths are what it caches.
    body = (
        "// GENERATED by scripts/stamp.py — do not edit.\n"
        "// Regenerate with `make stamp`.\n"
        f"self.SHELL_VERSION = {json.dumps(version)};\n"
        f"self.SHELL = {json.dumps(rel, indent=2)};\n"
    )
    path = ROOT / "sw-shell.js"
    old = path.read_text(encoding="utf-8") if path.exists() else ""
    if old != body:
        path.write_text(body, encoding="utf-8")
        return True
    return False


def main() -> int:
    files = shell_files()
    if not files:
        print("stamp: no shell files found", file=sys.stderr)
        return 1
    # index.html contains the hash itself, so hashing it would never settle.
    version = content_hash([f for f in files if f.name != "index.html"])
    a = stamp_index(version)
    b = write_sw_shell(version, files)
    state = "updated" if (a or b) else "unchanged"
    print(f"stamp: {version} ({len(files)} shell files, {state})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
